//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccountResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Josefina.Resources.AccountResources", typeof(AccountResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadaný email je již použit.
        /// </summary>
        public static string AlreadyExistsEmailError {
            get {
                return ResourceManager.GetString("AlreadyExistsEmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadané uživatelské jméno je již použito.
        /// </summary>
        public static string AlreadyExistsUsernameError {
            get {
                return ResourceManager.GetString("AlreadyExistsUsernameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Změna hesla.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vytvoření nového uživatelského účtu.
        /// </summary>
        public static string CreateNewAccount {
            get {
                return ResourceManager.GetString("CreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stávající heslo.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrace proběhla v pořádku.
        /// </summary>
        public static string DialogSuccesfullRegistration {
            get {
                return ResourceManager.GetString("DialogSuccesfullRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosím potvrďte svojí emailovou adresu kliknutím na odkaz v emailu, který byl odeslán na Vaši emailovou adresu..
        /// </summary>
        public static string DialogSuccesfullStartMessage {
            get {
                return ResourceManager.GetString("DialogSuccesfullStartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokračovat můžete přihlášením.
        /// </summary>
        public static string DialogSuccesfullStartMessageInvitation {
            get {
                return ResourceManager.GetString("DialogSuccesfullStartMessageInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vytvoření nové Organizace proběhlo úspěsně..
        /// </summary>
        public static string DialogSuccesfullyRegisteredOrgBody {
            get {
                return ResourceManager.GetString("DialogSuccesfullyRegisteredOrgBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vytvoření nového úživatelského účtu proběhlo úspěšně..
        /// </summary>
        public static string DialogSuccesfullyRegisteredUser {
            get {
                return ResourceManager.GetString("DialogSuccesfullyRegisteredUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email pro tento uživatelský účet byl již potvrzen.
        /// </summary>
        public static string EmailAlreadyConfirmed {
            get {
                return ResourceManager.GetString("EmailAlreadyConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrzení emailové adresy.
        /// </summary>
        public static string EmailConfirmation {
            get {
                return ResourceManager.GetString("EmailConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrzení Vaší emailové adresy proběhlo v pořádku.
        /// </summary>
        public static string EmailConfirmed {
            get {
                return ResourceManager.GetString("EmailConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uživatel s daným emailem nenalezen.
        /// </summary>
        public static string EmailDoesntExist {
            get {
                return ResourceManager.GetString("EmailDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadný email buď není registrován, nebo není potvrzen.
        /// </summary>
        public static string EmailDoesntExistOrNotConfirmed {
            get {
                return ResourceManager.GetString("EmailDoesntExistOrNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadejte svůj email.
        /// </summary>
        public static string EnterYourEmail {
            get {
                return ResourceManager.GetString("EnterYourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapomněli jste heslo?.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neplatný formát emailu.
        /// </summary>
        public static string InvalidEmailError {
            get {
                return ResourceManager.GetString("InvalidEmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neplatné heslo.
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadán neexistující email, nebo heslo.
        /// </summary>
        public static string InvalidUsernameOrPassword {
            get {
                return ResourceManager.GetString("InvalidUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přihlášení pomocí lokálního účtu.
        /// </summary>
        public static string LocalLogin {
            get {
                return ResourceManager.GetString("LocalLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přihlášení.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přihlásit se.
        /// </summary>
        public static string LogMeIn {
            get {
                return ResourceManager.GetString("LogMeIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spravovat uživatelský účet.
        /// </summary>
        public static string ManageAccount {
            get {
                return ResourceManager.GetString("ManageAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nové heslo.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrzení hesla.
        /// </summary>
        public static string NewPasswordConfirmation {
            get {
                return ResourceManager.GetString("NewPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nové heslo nesmí být stejné jako staré.
        /// </summary>
        public static string NewPasswordMustBeNew {
            get {
                return ResourceManager.GetString("NewPasswordMustBeNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosím potvrďte svojí emailovou adresu kliknutím na odkaz v emailu, který byl odeslán na Vaši emailovou adresu..
        /// </summary>
        public static string NotConfirmedEmailError {
            get {
                return ResourceManager.GetString("NotConfirmedEmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heslo.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Změna hesla proběhla v pořádku.
        /// </summary>
        public static string PasswordChanged {
            get {
                return ResourceManager.GetString("PasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obnovení hesla.
        /// </summary>
        public static string PasswordRecovery {
            get {
                return ResourceManager.GetString("PasswordRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Na vaší emailovou adresu byl odeslán email s odkazem pro obnovení hesla.
        /// </summary>
        public static string PasswordRecoveryEmailSent {
            get {
                return ResourceManager.GetString("PasswordRecoveryEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Změna uživatelského hesla proběhla v pořádku.
        /// </summary>
        public static string PasswordRecoverySuccesfull {
            get {
                return ResourceManager.GetString("PasswordRecoverySuccesfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pamatovat si přihlášení.
        /// </summary>
        public static string RememberLogin {
            get {
                return ResourceManager.GetString("RememberLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uživatelské jméno.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
    }
}
