//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OrgResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OrgResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Josefina.Resources.OrgResources", typeof(OrgResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizace s daným jménem již existuje.
        /// </summary>
        public static string AlreadyExistsError {
            get {
                return ResourceManager.GetString("AlreadyExistsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finanční dimenze.
        /// </summary>
        public static string FinancialDimension {
            get {
                return ResourceManager.GetString("FinancialDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daná pozvánka již byla přijata.
        /// </summary>
        public static string InvitationAlreadyAccepted {
            get {
                return ResourceManager.GetString("InvitationAlreadyAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pozvánka nemohla být odeslána, daný email je v aplikaci již použit.
        /// </summary>
        public static string InvitationCantBeSentAlreadyExistEmail {
            get {
                return ResourceManager.GetString("InvitationCantBeSentAlreadyExistEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pozvánka byla úspěšně odeslána.
        /// </summary>
        public static string InvitationSend {
            get {
                return ResourceManager.GetString("InvitationSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pozvánka do informačního systému Josefína.
        /// </summary>
        public static string InvitationTitle {
            get {
                return ResourceManager.GetString("InvitationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Josefína.
        /// </summary>
        public static string Josefina {
            get {
                return ResourceManager.GetString("Josefina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizace.
        /// </summary>
        public static string Organization {
            get {
                return ResourceManager.GetString("Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno organizace.
        /// </summary>
        public static string OrgName {
            get {
                return ResourceManager.GetString("OrgName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizace s daným jménem neexistuje.
        /// </summary>
        public static string OrgnameDoesntExist {
            get {
                return ResourceManager.GetString("OrgnameDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vytvoření organizace.
        /// </summary>
        public static string OrgRegistration {
            get {
                return ResourceManager.GetString("OrgRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vytvořte organizaci v rámci které budete plánovat jednotlivé projekty..
        /// </summary>
        public static string OrgRegistrationDescription {
            get {
                return ResourceManager.GetString("OrgRegistrationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odeslat pozvánku.
        /// </summary>
        public static string SendInvitation {
            get {
                return ResourceManager.GetString("SendInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Na zadanou adresu odešle email s pozvánkou do vaší Organizace. .
        /// </summary>
        public static string SendInvitationBody {
            get {
                return ResourceManager.GetString("SendInvitationBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odeslání povánky do systému.
        /// </summary>
        public static string SendInvitationTitle {
            get {
                return ResourceManager.GetString("SendInvitationTitle", resourceCulture);
            }
        }
    }
}
