//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProjectResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProjectResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Josefina.Resources.ProjectResources", typeof(ProjectResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projekt se stejným jménem a datem již existuje.
        /// </summary>
        public static string AlreadyExistingProjectError {
            get {
                return ResourceManager.GetString("AlreadyExistingProjectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zpět na seznam.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opravdu chcete smazat tento projekt?.
        /// </summary>
        public static string DeleteProjectHeader {
            get {
                return ResourceManager.GetString("DeleteProjectHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nový projekt.
        /// </summary>
        public static string NewProject {
            get {
                return ResourceManager.GetString("NewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projekt.
        /// </summary>
        public static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projekt vytvořen.
        /// </summary>
        public static string ProjectCreated {
            get {
                return ResourceManager.GetString("ProjectCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vytvoření nového projektu proběhlo úspěsně..
        /// </summary>
        public static string ProjectCreatedBody {
            get {
                return ResourceManager.GetString("ProjectCreatedBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projekt smazán.
        /// </summary>
        public static string ProjectDeleted {
            get {
                return ResourceManager.GetString("ProjectDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smazaní projektu proběhlu v pořádku..
        /// </summary>
        public static string ProjectDeletedBody {
            get {
                return ResourceManager.GetString("ProjectDeletedBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projekty.
        /// </summary>
        public static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projekt upraven.
        /// </summary>
        public static string ProjectUpdated {
            get {
                return ResourceManager.GetString("ProjectUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Úprava projektu proběhla v pořádku..
        /// </summary>
        public static string ProjectUpdatedBody {
            get {
                return ResourceManager.GetString("ProjectUpdatedBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyberter prosím nejprve projekt.
        /// </summary>
        public static string SelectProjectError {
            get {
                return ResourceManager.GetString("SelectProjectError", resourceCulture);
            }
        }
    }
}
